import Link from "next/link";

export const metadata = {
  title: "Terms of Service - Exai",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      {/* Nav */}
      <nav className="border-b border-gray-100 dark:border-zinc-800">
        <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <img src="/logo.png" alt="Exai" className="h-7 w-7 object-contain" />
            <span className="font-semibold text-gray-900 dark:text-white tracking-tight">Exai</span>
          </Link>
          <Link
            href="/auth"
            className="text-sm font-medium text-gray-500 dark:text-zinc-400 hover:text-gray-900 dark:hover:text-white transition-colors"
          >
            Sign in
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <p className="text-sm text-gray-400 dark:text-zinc-500 mb-2">Last updated: March 2026</p>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Terms of Service</h1>
          <p className="mt-3 text-gray-500 dark:text-zinc-400 leading-relaxed">
            By using Exai, you agree to these Terms of Service. Please read them carefully.
          </p>
        </div>

        <div className="space-y-10 text-gray-700 dark:text-zinc-300">

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">1. Use of Service</h2>
            <p className="leading-relaxed">
              Exai is a study tool intended for students preparing for university exams, quizzes, and assessments.
              You may use Exai for personal, non-commercial study purposes.
            </p>
            <p className="leading-relaxed">
              You must not use Exai in any way that violates applicable laws or these Terms.
            </p>
            <p className="leading-relaxed">
              You must be at least 13 years of age to use Exai. By creating an account, you confirm that you meet this requirement.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">2. AI Generated Content</h2>
            <p className="leading-relaxed">
              Exai uses artificial intelligence to generate practice questions, explanations, and grading feedback.
            </p>
            <p className="leading-relaxed">
              AI-generated content may contain mistakes, inaccuracies, or outdated information.
            </p>
            <p className="leading-relaxed">
              You are responsible for verifying the accuracy of any content generated by Exai before relying on it for academic or other purposes. Exai is a practice tool and is not a substitute for official course materials, instructors, or educational institutions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">3. User Content</h2>
            <p className="leading-relaxed">
              You retain ownership of the files and materials you upload to Exai.
            </p>
            <p className="leading-relaxed">
              By uploading content, you grant Exai a limited license to process, store, and analyze that content solely for the purpose of providing the service to you.
            </p>
            <p className="leading-relaxed">
              You are solely responsible for the materials you upload. You must not upload:
            </p>
            <ul className="space-y-2 pl-4">
              {[
                "Content that infringes on the intellectual property rights of others without authorization.",
                "Illegal, harmful, or offensive material.",
                "Personal data of others without their consent.",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2 leading-relaxed">
                  <span className="mt-2 w-1.5 h-1.5 rounded-full bg-gray-400 dark:bg-zinc-500 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
            <p className="leading-relaxed">
              You may not use Exai to generate content for academic cheating, plagiarism, or other dishonest academic activities.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">4. Service Availability</h2>
            <p className="leading-relaxed">
              Exai is provided on a best-effort basis.
            </p>
            <p className="leading-relaxed">
              We may modify, suspend, or discontinue features or the service itself at any time, with or without notice.
            </p>
            <p className="leading-relaxed">
              We are not liable for interruptions, delays, or changes to the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">5. Limitation of Liability</h2>
            <p className="leading-relaxed">
              Exai is provided &quot;as is&quot; without warranties of any kind, express or implied.
            </p>
            <p className="leading-relaxed">We do not guarantee that:</p>
            <ul className="space-y-2 pl-4">
              {[
                "the service will be error-free",
                "the service will always be available",
                "AI-generated content will be accurate or reliable",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2 leading-relaxed">
                  <span className="mt-2 w-1.5 h-1.5 rounded-full bg-gray-400 dark:bg-zinc-500 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
            <p className="leading-relaxed">
              To the fullest extent permitted by law, Exai and its operators are not liable for any indirect, incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">6. Account Responsibility</h2>
            <p className="leading-relaxed">
              You are responsible for all activity that occurs under your account.
            </p>
            <p className="leading-relaxed">
              You must keep your login credentials secure and must not share your account with others.
            </p>
            <p className="leading-relaxed">
              If you suspect unauthorized access to your account, you must notify us as soon as possible.
            </p>
            <p className="leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate these Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">7. Payments and Subscriptions</h2>
            <p className="leading-relaxed">
              Some features of Exai require payment. Payments are processed through our payment provider, Paddle.
            </p>
            <p className="leading-relaxed">
              By purchasing premium features or subscriptions, you agree to the pricing and billing terms presented at checkout.
            </p>
            <p className="leading-relaxed">Exai currently offers:</p>
            <ul className="space-y-2 pl-4">
              {[
                "Per-course premium upgrades",
                "A full premium subscription",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2 leading-relaxed">
                  <span className="mt-2 w-1.5 h-1.5 rounded-full bg-gray-400 dark:bg-zinc-500 shrink-0" />
                  {item}
                </li>
              ))}
            </ul>
            <p className="leading-relaxed">
              Subscriptions may renew automatically unless canceled before the renewal date. You may manage or cancel your subscription through the billing management tools provided by Paddle.
            </p>
            <p className="leading-relaxed">
              Prices may change in the future, but changes will not affect your current billing period.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">8. Refunds</h2>
            <p className="leading-relaxed">
              Because Exai provides digital services, purchases are generally non-refundable, unless required by applicable law.
            </p>
            <p className="leading-relaxed">
              If you believe you were charged incorrectly or experienced a billing issue, please contact support and we will review your request.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">9. Changes to These Terms</h2>
            <p className="leading-relaxed">
              We may update these Terms of Service from time to time. When we make changes, we will update the &quot;Last updated&quot; date at the top of this page.
            </p>
            <p className="leading-relaxed">
              Continued use of Exai after changes are posted constitutes your acceptance of the updated Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">10. Governing Law</h2>
            <p className="leading-relaxed">
              These Terms shall be governed by and interpreted in accordance with the laws of the jurisdiction in which the service operator resides, without regard to conflict of law principles.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">11. Contact</h2>
            <p className="leading-relaxed">
              If you have questions about these Terms, you may contact us at{" "}
              <a href="mailto:support@exai.study" className="underline underline-offset-2 hover:text-gray-900 dark:hover:text-white transition-colors">
                support@exai.study
              </a>
            </p>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-100 dark:border-zinc-800 mt-16">
        <div className="max-w-5xl mx-auto px-6 py-6 flex items-center justify-between gap-4 text-sm text-gray-400 dark:text-zinc-500">
          <span>© {new Date().getFullYear()} Exai</span>
          <div className="flex items-center gap-4">
            <Link href="/privacy" className="hover:text-gray-700 dark:hover:text-zinc-300 transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-gray-700 dark:hover:text-zinc-300 transition-colors">Terms</Link>
            <a href="mailto:support@exai.study" className="hover:text-gray-700 dark:hover:text-zinc-300 transition-colors">support@exai.study</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
